// src/components/PageContent.vue
<template>
  <main>
    <header>
      <h2
        class="title"
        @mousedown="
          () => {
            showHint = true;
            setTimeout(() => {
              showHint = false;
            }, 500);
          }
        "
      >
        <template v-if="page">
          {{ page.title }}
          <Transition name="fade">
            <span
              v-if="showHint"
              style="
                font-weight: 100;
                font-style: italic;
                font-size: 0.6em;
                vertical-align: middle;
              "
            >
              - Nothing here
            </span>
          </Transition>
        </template>
        <template v-else> 404 - Page not found </template>
      </h2>
    </header>
    <template v-if="page">
      <Paragraph
        v-for="(paragraph, index) in page.body"
        :key="index"
        :paragraph="paragraph"
        :last="index + 1 === page.body.length"
      />
    </template>
    <template v-else>
      <Paragraph
        :paragraph="`The page <strong>${$route.params.pathMatch[0]}</strong> does not exist!`"
        :last="true"
      />
    </template>
  </main>
</template>

<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { useRoute } from "vue-router";
import pages from "../configs/pages.json";
import Paragraph from "./Paragraph.vue";
import { Page } from "../interfaces/Page";

const showHint = ref(false);
const route = useRoute();

const page = computed(() => {
  if (route.params.name) {
    return (
      pages.find((p) => p.link.slice(1) === route.params.name) || pages[0]
    );
  }
  if (route.params.pathMatch) {
    return null;
  }
  return pages[0];
});

watch(
  () => route.params.name,
  () => {
    const newPage =
      pages.find((p) => p.link.slice(1) === route.params.name) || pages[0];
    if (newPage) {
      document.title = "Elliot > " + newPage.title;
    }
  },
  { immediate: true },
);
</script>

// src/components/PageContent.tsx
import { Component, createEffect, createSignal, For, Show } from "solid-js";
import pages from '../configs/pages.json';
import { Paragraph } from "./Paragraph";
import { Transition } from "solid-transition-group";
import { useParams } from "@solidjs/router";
import {Page} from "../interfaces/Page";

export const PageContent: Component = () => {
  const [ showHint, setShowHint ] = createSignal<boolean>(false);
  const [ page, setPage ] = createSignal<Page>(pages[0]);

  const headingClasses = {
    title: true,
  };

  if (useParams().incorrect != undefined) {
    const incorrect = useParams().incorrect;

    return (
      <main>
        <header>
          <h2
            classList={ headingClasses }
            onMouseDown={ () => {
              setShowHint(true);
              setTimeout(() => {
                setShowHint(false);
              }, 500);
            } }
          >404 - Page not found
          </h2>
        </header>
        <Paragraph paragraph={ `The page <strong>${ incorrect }</strong> does not exist!` } last={ true }/>
      </main>
    );
  }

  createEffect(() => {
    const currentPage = pages.find((page) => page.link.slice(1) === useParams().name);
    setPage(currentPage || pages[0]);
  });

  const fadeIn = (el: Element, done: () => void): void => {
    const a = el.animate([ { opacity: 0 }, { opacity: 1 } ], {
      duration: 500
    });
    a.finished.then(done);
  };
  const fadeOut = (el: Element, done: () => void): void => {
    const a = el.animate([ { opacity: 1 }, { opacity: 0 } ], {
      duration: 500
    });
    a.finished.then(done);
  };

  return (
    <main>
      <header>
        <h2
          classList={ headingClasses }
          onMouseDown={ () => {
            setShowHint(true);
            setTimeout(() => {
              setShowHint(false);
            }, 500);
          } }
        >{ page().title }
          <Transition onEnter={ fadeIn } onExit={ fadeOut }>
            <Show when={ showHint() }>
              <span
                style="font-weight: 100;font-style: italic;font-size:0.6em;vertical-align: middle;"> - Nothing here</span>
            </Show>
          </Transition>
        </h2>
      </header>
      <For each={ page().body }>{
        (paragraph, index) => <Paragraph paragraph={ paragraph } last={ index() + 1 === page().body.length }/>
      }</For>
    </main>
  );
};
